Disable all flake8 checks not indicating errors
With this change in place, here's what I get from flake8. Especially the
warningas about accessing undefined variables are suspicious:
```
src/blam.py:38:1: F811 redefinition of unused 'math' from line 20
src/blam.py:249:42: F812 list comprehension redefines 'r' from line 246
src/blam.py:375:5: F841 local variable 'cIn' is assigned to but never used
src/blam.py:696:13: F841 local variable 'f' is assigned to but never used
src/blam.py:943:9: F841 local variable 'Qba' is assigned to but never used
src/blam.py:947:9: F841 local variable 'Qca' is assigned to but never used
src/blam.py:948:9: F841 local variable 'Qcb' is assigned to but never used
src/blam.py:1145:9: F841 local variable 'k1' is assigned to but never used
src/blam.py:1146:9: F841 local variable 'firstFace' is assigned to but never used
src/blam.py:1210:32: F821 undefined name 'f10Idx'
src/blam.py:1224:32: F821 undefined name 'f10dx'
src/blam.py:1435:9: F841 local variable 'scn' is assigned to but never used
src/blam.py:1611:9: F841 local variable 'FuFv' is assigned to but never used
```